spring.application.name=POULTRY-ERP-API-NEW

server.port=9092


#Database LOCAL Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/quickero_kastoori
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Database LIVE Configuration-1
#spring.datasource.url=jdbc:mysql://localhost:3306/codespir_demoapp?autoReconnect=true&useSSL=false
#spring.datasource.username=codespir_root
#spring.datasource.password=Maradona@123
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver


#Database LIVE Configuration-2
spring.datasource.url=jdbc:mysql://localhost:3306/quickero_ksagro?autoReconnect=true&useSSL=false
spring.datasource.username=quickero_root
spring.datasource.password=Maradona@123
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#file.upload-dir=/home/codespir/uploads/images


file.upload-dir-mortility=/home/quickero/apache-tomcat-9/webapps/erp/mobile_upload/mortility
file.upload-dir-travel=/home/quickero/apache-tomcat-9/webapps/erp/mobile_upload/travel
file.base-url=https://www.codespiraltechnologies.com/images

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Naming strategy (you can keep as-is)
##COMMENT FOR LOCAL ENVIRONMENT
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

# MySQL dialect (IMPORTANT CHANGE)
##COMMENT FOR LOCAL ENVIRONMENT
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



#JPA Configurations
spring.jpa.show-sql=true
#For Creating schemas and tables
spring.jpa.hibernate.ddl-auto=none
